### ISSUE TITLE
py3.10 dependency conflict

### ISSUE THREAD

**Issue by DTwz** [opendatalab/Miner-PDF-Benchmark#1]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairy-doc 0.1.30 requires pytz==2024.1, but you have pytz 2023.4 which is incompatible.
fairy-doc 0.1.30 requires requests==2.32.2, but you have requests 2.28.2 which is incompatible.
fast-langdetect 0.1.1 requires requests>=2.31.0, but you have requests 2.28.2 which is incompatible.

**Comment by del-zhenwu** [comment]
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. fairy-doc 0.1.30 requires pytz==2024.1, but you have pytz 2023.4 which is incompatible. fairy-doc 0.1.30 requires requests==2.32.2, but you have requests 2.28.2 which is incompatible. fast-langdetect 0.1.1 requires requests>=2.31.0, but you have requests 2.28.2 which is incompatible.

Thank you for reporting this issue, we will update the `requirements`.

**Comment by dt-yy** [comment]
The issue has been resolved by adopting Python version 3.9
