### ISSUE TITLE
验证集事实错误, 使用未经清洗的Mathpix数据作为ground truth

### ISSUE THREAD

**Issue by circlestarzero** [opendatalab/Miner-PDF-Benchmark#10]
验证集存在大量的Mathpix图床以及识别错误, 很多公式甚至都无法渲染, 请问贵方作为上海人工智能实验室, 做这种 benchmark 这么学术不严谨合理吗?

[如何评价Miner-PDF-Benchmark直接使用未经过清洗的Mathpix识别结果作为验证集?](https://www.zhihu.com/question/660751770)

![2b65aead95089b2d2701fc15ae6f8929](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/17841208-d1b1-417a-8f5d-67ecf11b86c2)

贵方提交annotations的commit:
https://github.com/DTwz/Miner-PDF-Benchmark/commit/963e540df4cd0e391c5a6bf873b7d7feabf1955d
鉴于这个repo删库跑路了, 下面是补档的commit:
https://github.com/circlestarzero/Miner-PDF-Benchmark/commit/963e540df4cd0e391c5a6bf873b7d7feabf1955d

![a2dfa6fa091b63e132ae19dda9685bda](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/0930003f-7c60-4866-a668-94e367935599)
![d2a8de4821f4857d0f83ac40efd1dd91](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/859b1cca-0246-47c6-9dd2-3bf393dea9aa)
![8d9225a35cca8bd7e8708557b886cd33](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/9e4548db-f688-42f8-ae10-4ae2b8042157)
![3a6e65d0c6c2175e9b03558a290c5e36](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/bfc9cdab-0893-4100-aad0-e039268bacf4)

**Comment by dt-yy** [comment]
MPB评测集是全量经过人工标注的，公式正确性判断是通过能否在overleaf渲染为标准， 存在部分公式是通过截图的方式；

**Comment by circlestarzero** [comment]
> MPB评测集是全量经过人工标注的，公式正确性判断是通过能否在overleaf渲染为标准， 存在部分公式是通过截图的方式；

commit就在那里摆着呢, 你告诉我人工标注, 可笑
https://github.com/circlestarzero/Miner-PDF-Benchmark/commit/963e540df4cd0e391c5a6bf873b7d7feabf1955d

**Comment by circlestarzero** [comment]
https://cdn.mathpix.com/cropped/2024_04_26_6fdc9a16073a10ec4f2ag-24.jpg?height=112&width=907&top_left_y=1039&top_left_x=601

https://cdn.mathpix.com/cropped/2024_04_26_6fdc9a16073a10ec4f2ag-24.jpg

![2024_04_26_6fdc9a16073a10ec4f2ag-24](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/23fe995a-5726-4924-9b55-8d54a7c82893)

上述图片的原图, 来自mathpix cdn

**Comment by circlestarzero** [comment]
更多验证集错误我将在知乎更新:
[如何评价Miner-PDF-Benchmark直接使用未经过清洗的Mathpix识别结果作为验证集?](https://www.zhihu.com/question/660751770)

**Comment by e06084** [comment]
感谢您的关注和反馈。

目前的验证集也还在完善阶段，上面的issue回复可能有些不严谨，这里再补充回复一下。

当前验证集版本的groudtruth构建过程是先通过mathpix抽取为markdown文件，再进行人工标注。构建过程可以参考README中“验证集构建方法”章节，有更详细的介绍。

我们也针对grouptruth中的图片补充做了一次人工统计，当前grouptruth版本中确实存在的少量公式图和表格图片。这个误差可能会给评测结果带来一些影响，我们会在后续验证集迭代版本中优化解决。

@circlestarzero

**Comment by e06084** [comment]
欢迎关注我们新的评测集：https://github.com/opendatalab/OmniDocBench
