### ISSUE TITLE
咨询：新的评测集什么时候开源（Q3）

### ISSUE THREAD

**Issue by RDSJC** [opendatalab/Miner-PDF-Benchmark#20]
看之前的issue说Q3开源，Q3还剩一个月了，有最新计划吗

**Comment by e06084** [comment]
您好，感谢关注。

下一个版本我们计划会加入更细化的模块评测指标（表格，公式等），所以耗时比预期要久一些，目前计划会在Q4开源。敬请期待。

**Comment by RDSJC** [comment]
之前开源的那版数据能提供一份吗

**Comment by e06084** [comment]
目前没有计划提供，计划在下一版本中再提供，因为数据集内容也会有一些调整。

**Comment by e06084** [comment]
@RDSJC 新版开源见：https://github.com/opendatalab/OmniDocBench
