### ISSUE TITLE
测试指标无法反映PDF2MD的真实性能

### ISSUE THREAD

**Issue by Muxv** [opendatalab/Miner-PDF-Benchmark#6]
项目中使用编辑距离, BLEU等指标来衡量包含公式的`PDF2MD`准确度, 这明显是不合理的
公式内可以随意增减`{}`数量但表达的意思是相同的

```python
>>> from Levenshtein import distance
>>> a = 'a^{1}'
>>> b = 'a^1'
>>> c = '{a}^{1}'
>>> distance(b, a)
2
>>> distance(b, b)
0
>>> distance(b, c)
4
```
此外关于表格相似度的衡量, 标准markdown语法不支持合并单元格的表达, 应该使用html或latex表格语法来衡量
项目中关于衡量相似度的指标过于简陋, 并不适合判断各种`PDF2MD`工具的优劣
望改进

**Comment by Muxv** [comment]
此外,

**Comment by circlestarzero** [comment]
同问, 数据集的生成是否是使用mathpix识别纠正的, 这样mathpix的指标当然虚高

**Comment by dt-yy** [comment]
目前由于latex公式版本不一致，是评估说明的已知问题
![image](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/102640628/886500c1-faae-4e26-b557-03a85c9e0554)

**Comment by e06084** [comment]
感谢您的关注和反馈。

在我们之前的调研结果中，当前pdf抽取性能评估指标业界还没有非常完美的指标（都会在某些场景下存在一些不准确性），所以我们验证集参考了一些抽取工具中使用到的3个评估指标（bleu、edit distance、similarity）。详细的指标的定义请参考README中“指标”章节介绍。

欢迎推荐更多样化的评估指标，我们会考虑在后续的评测版本中添加。

@Muxv

**Comment by e06084** [comment]
欢迎关注我们新的评测集：https://github.com/opendatalab/OmniDocBench
