### ISSUE TITLE
验证集明显不合理, 使用mathpix识别未清洗得到的数据作为ground truth, 这样将导致mathpix得分明显虚高

### ISSUE THREAD

**Issue by circlestarzero** [opendatalab/Miner-PDF-Benchmark#7]

**Comment by circlestarzero** [comment]
![8d9225a35cca8bd7e8708557b886cd33](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/75794159/5aec550b-0312-4f30-af5d-8ccb3e879b33)

如公布的数据集的annotation展示, 多处出现mathpix的cdn图片, 合理怀疑是使用mathpix识别纠正

**Comment by circlestarzero** [comment]
# gpt4o评价
使用Mathpix纠正的结果作为文档识别评测benchmark的groundtruth来衡量Mathpix和其他工具会带来明显的不合理性和偏差，具体影响如下：

	1.	引入工具偏见：
	•	偏向性：因为groundtruth是基于Mathpix纠正的结果，那么Mathpix自身在这个groundtruth上表现会优于其他工具。这是因为Mathpix的groundtruth自然符合其自身的特性和错误模式，而其他工具可能会因为这些偏差而被不公平地评估。
	2.	失去独立性和客观性：
	•	缺乏独立验证：groundtruth数据集应当是独立、真实的数据，以便公平地评估不同工具的性能。使用Mathpix的结果作为groundtruth会失去这种独立性，评估结果会偏向Mathpix。
	3.	过拟合风险：
	•	特定模式拟合：Mathpix纠正的结果可能包含特定的错误模式和偏差，评估工具时这些模式会影响其他工具的表现，导致评估结果失真。
	4.	评估结果不公平：
	•	不公平比较：其他工具在评估时，其错误率和准确率可能会因为Mathpix的特有偏差而受到不公平的负面影响。评估结果会显示Mathpix比其他工具表现更好，即使在独立数据集上可能并非如此。
	5.	影响benchmark的普适性：
	•	普适性降低：一个好的benchmark应当具有普适性，能够广泛适用于各种工具和场景。使用特定工具纠正的结果作为groundtruth会降低benchmark的普适性，无法准确反映工具在不同情境下的真实性能。

更合理的方法

为了确保评估的公正性和科学性，应使用独立的、未见过的数据作为groundtruth。这些数据应当多样化，包含不同类型的文本和噪声，以全面衡量各个OCR工具的性能。

总结

使用Mathpix纠正的结果作为groundtruth来评估Mathpix和其他工具是不合理的，会导致偏差和不公平的评估结果。为了确保评估的科学性和公正性，groundtruth数据集应当是独立的、真实的、未经过任何特定工具处理的数据集。

**Comment by e06084** [comment]
感谢您的关注和反馈。

目前的验证集还在完善阶段，该问题我们在 https://github.com/opendatalab/Miner-PDF-Benchmark/issues/10 这个issue有回复，请关注该issue后续讨论。

**Comment by e06084** [comment]
欢迎关注我们新的评测集：https://github.com/opendatalab/OmniDocBench
