### ISSUE TITLE
There seem have some accuracy issues with the validation set

### ISSUE THREAD

**Issue by cloudwallker** [opendatalab/Miner-PDF-Benchmark#8]
I randomly checked the data in several validation sets and found that there seems to be a fairly serious problem with the correctness of them:

Example1, latex formula error not displaying correctly:
![1](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/130576116/50420f1f-a201-461a-86ed-b147cfeb2448)

Example2, also latex formula error not displaying correctly:
![2](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/130576116/18b8d709-22b5-4b64-8207-eaf9d802d863)

Example3, it looks like mathpix handled the error by returning the image directly(**Why is there a link to a picture of mathpix in the validation set?**)
![3](https://github.com/opendatalab/Miner-PDF-Benchmark/assets/130576116/f70997c9-3a6b-4a12-ac18-0c5d0990d13e)

**Comment by e06084** [comment]
感谢您的关注和反馈。
目前的验证集还在完善阶段，该问题我们在 https://github.com/opendatalab/Miner-PDF-Benchmark/issues/10 这个issue有回复，请关注该issue后续讨论。

**Comment by e06084** [comment]
欢迎关注我们新的评测集：https://github.com/opendatalab/OmniDocBench
